controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    # curtis_motor_velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# curtis_motor_velocity_controller:
#   ros__parameters:
#     joints:
#       - curtis_motor
#     interface_name: velocity
#     command_interfaces:
#       - throttle
#     state_interfaces:
#       - velocity
#       - current_rms
#       - battery_current
#       - voltage
#       - bdi_percentage
#       - motor_rpm
#       - temperature
#       - motor_temperature